config/routes.rb
Rails.application.routes.draw do



  #definimos el root_path
  root :to => 'auth#index'


  # User´s authentication
  get '/login' => 'auth#new'
  post '/login' => 'auth#create'
  get '/logout' => 'auth#destroy'

  #routes de la order
  resources :orders
  get '/orders/receivable/:id', to: 'orders#receivable'
  get '/orders/sendKitchen/:id', to: 'orders#sendKitchen'
  get '/orders_history', to: 'orders#history'
  get '/charges', to: 'charges#kitchen'
  get '/filterOrdersKitchen', to: 'charges#filterOrdersKitchen'

  resources :plates
  get '/platesFilterCategory', to: 'plates#filterDishes'

  resources :tables, except: :show
  resources :categories,except: :show
  resources :users
  resources :profiles,except: :show


  #Routes agregar platos a la orders_path
  get '/orders/:id/plates', to: 'charges#index'
  #ruta parra filtrar platos al añadir plato
  get '/orders/:id/plates', to: 'charges#filterDishes'
  #borra y anadir platos a la comanda
  get '/orders/:id/plates/questionnaire' => 'charges#questionnaire'
  post '/addCharge', to: 'charges#addCharge'
  delete '/removeCharge', to: 'charges#removeCharge'


  #Route para marcar plato como preparado
  post '/preparedDish', to: 'charges#preparedDish'

#rutas de la version 2
  resources :answers, except: :show
  resources :questions, except: :show
  #resources :dishes_products,except: [:show, :index]
  resources :products, except: :show
  resources :posts
  resources :stocks, except: :show

  #rutas para asiganr productos a un plato
  get 'plates/:id/products', to: 'dishes_products#index'
  get 'plates/:id/products/new', to: 'dishes_products#new'
  post 'plates/:id/products/new', to: 'dishes_products#create'
  get 'plates/:id/products/edit/:registro', to: 'dishes_products#edit'
  post 'plates/:id/products/edit/:registro', to: 'dishes_products#update'
  delete 'plates/:id/products/:registro', to: 'dishes_products#destroy'

  match "*path" => 'auth#notFound', via: [:get, :post]

end

app/models/plate.rb
class Plate < ApplicationRecord
  belongs_to :category
  has_many :charges
  has_many :orders, through: :charges

  has_many :dishes_products
  has_many :products, through: :dishes_products

  before_destroy :removePhoto
  before_save :savePhoto

  validates :category_id,:name,:price,:description, presence: true
  validates :photo, presence:true, :on => :create
  validates :price, :numericality  => {only_float:true}
  validates :name, :length => {:minimum =>3}
  validates :description, :length => {minimum: 10, maximum:1000}

  ROUTES_PHOTOS = "app/assets"
  DIR_PHOTOS = "images"
  @image = nil
  def validateImage(image)
    fails = 0
    if !image.nil?
      if image.original_filename.split('.').last.downcase != 'jpg'
        errors.add(:photo, "JPG format allowed")
        fails += 1
      end
      if image.size > 1.megabytes
        errors.add(:photo, "Maximum allowed size 1 MB")
        fails += 1
      end
      if fails == 0
        status = true
        @image = image
      else
        status = false
      end
    else
      errors.add(:photo, "Photo can´t be black")
      status = false
    end
    return status
  end

  def checkDependences
    return self.orders.count == 0 && self.charges.count == 0
  end

private
  def savePhoto
    route_old_photo = self.photo_was
    if (@image.nil?)
        self.photo = route_old_photo
    else
      if !route_old_photo.nil? && File.exist?(ROUTES_PHOTOS+"/"+DIR_PHOTOS+"/"+route_old_photo)
          FileUtils.rm(ROUTES_PHOTOS+"/"+DIR_PHOTOS+"/"+route_old_photo)
      end
      name_photo = self.name.sub(' ', '')
      extension = @image.original_filename.split('.').last
      File.open(Rails.root.join(ROUTES_PHOTOS, DIR_PHOTOS, name_photo+"."+extension), 'wb') do |file|
        file.write(@image.read)
      end
      self.photo = name_photo+"."+extension
    end
    @image = nil
  end

  def removePhoto
    if File.exist?(ROUTES_PHOTOS+"/"+DIR_PHOTOS+"/"+self.photo)
        FileUtils.rm(ROUTES_PHOTOS+"/"+DIR_PHOTOS+"/"+self.photo)
    end
  end



end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :set_plate, only: [:show, :edit, :update, :destroy]
  before_action :createDishesPermissions, only:[:edit, :update,:destroy]
  # GET /plates
  # GET /plates.json
  def index
    @plates = Plate.all.paginate(page: params[:page], per_page: 8)
    @categories = Category.all
  end

  def filterDishes
    @category_selection = params[:category_selection]
    @plates = Plate.all.paginate(page: params[:page], per_page: 8)
    if @category_selection .present?
        @plates = Plate.where(category_id: @category_selection).paginate(page: params[:page], per_page: 8)
    end
    @categories = Category.all
    render :index
  end



  # GET /plates/1
  # GET /plates/1.json
  def show
  end

  # GET /plates/new
  def new
    @plate = Plate.new
    @categories = Category.all
  end

  # GET /plates/1/edit
  def edit
    @categories = Category.all
  end

  # POST /plates
  # POST /plates.json
  def create
    @plate = Plate.new(plate_params)
    respond_to do |format|
      if  @plate.validateImage(params[:plate][:photo]) && @plate.save
        format.html { redirect_to @plate, notice: 'Plate was successfully created.' }
        format.json { render :show, status: :created, location: @plate }
      else
        @categories = Category.all
        format.html { render :new }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plates/1
  # PATCH/PUT /plates/1.json
  def update
    #@plate.removePhoto
    respond_to do |format|
      if @plate.validateImage(params[:plate][:photo]) && @plate.update(plate_params)
          format.html { redirect_to @plate, notice: 'Plate was successfully updated.' }
          format.json { render :show, status: :ok, location: @plate }
      else
        @categories = Category.all
        format.html { render :edit }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plates/1
  # DELETE /plates/1.json
  def destroy
    if @plate.checkDependences
      @plate.destroy
      respond_to do |format|
        format.html { redirect_to plates_url, notice: 'Plate was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        flash[:notice_bad] = 'You can´t delete it. This element has dependencies.'
        format.html { redirect_to plates_url }
        format.json { head :no_content }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate
      @plate = Plate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_params
      params.require(:plate).permit(:category_id, :name, :description, :price, :photo)
    end
end

app/helpers/plates_helper.rb
module PlatesHelper
  def showEditingPermissions
    return session[:auth]["create_plate"]
  end
end

app/views/plates/_form.html.erb
<div class="col-md-10 forms-centers">


<%= form_for(plate, :multipart => true) do |f| %>
  <% if plate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plate.errors.count, "error") %> prohibited this plate from being saved:</h2>

      <ul>
      <% plate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-4 col-xs-12">
    <div class="field">
      <%= f.label :category_id %>
      <%= f.select :category_id, options_for_select(@categories.map{ |c| [c.name, c.id ]},plate.category_id),{}, { class: 'form-control form-control-sm'} %>
    </div>
  </div>
  <div class="col-md-8 col-xs-12">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name ,class:"form-control form-control-sm" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description ,class:"form-control form-control-sm" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-xs-12">
    <div class="field">
      <%= f.label :photo %>
      <%= f.file_field :photo ,class:"form-control form-control-sm" %>
    </div>
  </div>
  <div class="col-md-2 col-xs-12">
    <div class="field">
      <%= f.label :price %>
      <%= f.text_field :price ,class:"form-control form-control-sm" %>
    </div>
  </div>
</div>
<br>

  <div class="actions">
    <%= link_to '<<', plates_path ,class:"btn btn-default btn-sm" %>
    <%= f.submit 'Save', class:"btn btn-default btn-sm"%>
  </div>
<% end %>
</div>

app/views/plates/edit.html.erb
<h1 class="head-title-form"> Editing Dish</h1>
<div class="container">
<%= render 'form', plate: @plate %>

</div>

app/views/plates/index.html.erb
<h1 class="head-title-form"> Dishes</h1>
  <div class="container">
    <% if !notice.nil? %>
    <p id="notice" class="notice-bad"><%= notice %></p>
    <% end %>
    <% if (flash[:notice_bad])  %>
    <p id="notice_bad" class="notice-bad"><%= flash[:notice_bad] %></p>
    <% end %>
    <div class="row">

    <div class="col-md-12 col-xs-12">
      <%= form_tag("/platesFilterCategory", method: "get") do %>
        <%= select_tag(:category_selection ,options_for_select(@categories.map{ |c| [c.name, c.id ]},@category_selection),{include_blank: "Select category filter", onchange: "this.form.submit()", class: 'form-control form-control-sm'}) %>
      <% end %>
    </div>
    <br><br>

  <% @plates.each do |plate| %>
    <div class="col-md-3 col-xs-12 float_left_plates">
      <div class="row">
        <div class="col">
          <h3 class="title_plate_menu text-center">Nº<%= plate.id %>: <%= plate.name %></h3>
          <%= image_tag(plate.photo, :alt => "logo",  class:"images_plates_menu img-fluid") %>
        </div>
      </div>
      <div class="row">

      </div>
      <div class="row">
        <div class="col">
          <%= link_to 'Show', plate ,class: "btn btn-default btn-sm col-12" %>
        </div>
        <% if showEditingPermissions %>
        <div class="col">
            <%= link_to 'Edit', edit_plate_path(plate),class: "btn btn-default btn-sm col-12" %>
        </div>
        <div class="col">
            <%= link_to 'Destroy', plate, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-default btn-sm col-12" %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


</div>

<div class="row footer">
  <div class="col-md-12 col-xs-12">
    <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @posts, :container => false,:page_links => false %>
  </div>
  </div>
</div>

app/views/plates/new.html.erb
<h1 class="head-title-form"> New Dish</h1>
<div class="container">
<%= render 'form', plate: @plate %>

</div>

app/views/plates/show.html.erb
<h1 class="head-title-form"> Dish</h1>
<div class="container">

<div class="row">
  <div class="col-md-6 col-xs-12">
      <p><b>Photo:</b></p>
    <%= image_tag(@plate.photo, :alt => "logo",  class:"img-fluid") %>
  </div>
  <div class="col-md-6 col-xs-12">
    <div class="row">
      <div class="col-md-12 col-xs-12">
        <p><b>Category:</b></p>
        <i><%= @plate.category.name %></i>
      </div>
    </div>
    <div class="row">
      <div class="col-md-9 col-xs-12">
        <p><b>Name:</b></p>
        <i><%= @plate.name %></i>
      </div>
      <div class="col-md-3 col-xs-12">
      <p>  <b>Price:</b></p>
        <i><%= @plate.price %> €</i>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-xs-12">
        <p><b>Description:</b></p>
        <i><%= @plate.description %></i>
      </div>
    </div>
  </div>
</div>






<%= link_to '<<', plates_path,class: "btn btn-default btn-sm" %>
<% if showEditingPermissions %>
  <%= link_to 'Edit', edit_plate_path(@plate),class: "btn btn-default btn-sm" %>
  <%= link_to 'Add Products' ,'/plates/'+@plate.id.to_s+'/products' ,class: "btn btn-default btn-sm" %>
<% end %>
</div>