config/routes.rb
Rails.application.routes.draw do



  #definimos el root_path
  root :to => 'auth#index'


  # User´s authentication
  get '/login' => 'auth#new'
  post '/login' => 'auth#create'
  get '/logout' => 'auth#destroy'

  #routes de la order
  resources :orders
  get '/orders/receivable/:id', to: 'orders#receivable'
  get '/orders/sendKitchen/:id', to: 'orders#sendKitchen'
  get '/orders_history', to: 'orders#history'
  get '/charges', to: 'charges#kitchen'
  get '/filterOrdersKitchen', to: 'charges#filterOrdersKitchen'

  resources :plates
  get '/platesFilterCategory', to: 'plates#filterDishes'

  resources :tables, except: :show
  resources :categories,except: :show
  resources :users
  resources :profiles,except: :show


  #Routes agregar platos a la orders_path
  get '/orders/:id/plates', to: 'charges#index'
  #ruta parra filtrar platos al añadir plato
  get '/orders/:id/plates', to: 'charges#filterDishes'
  #borra y anadir platos a la comanda
  get '/orders/:id/plates/questionnaire' => 'charges#questionnaire'
  post '/addCharge', to: 'charges#addCharge'
  delete '/removeCharge', to: 'charges#removeCharge'


  #Route para marcar plato como preparado
  post '/preparedDish', to: 'charges#preparedDish'

#rutas de la version 2
  resources :answers, except: :show
  resources :questions, except: :show
  #resources :dishes_products,except: [:show, :index]
  resources :products, except: :show
  resources :posts
  resources :stocks, except: :show

  #rutas para asiganr productos a un plato
  get 'plates/:id/products', to: 'dishes_products#index'
  get 'plates/:id/products/new', to: 'dishes_products#new'
  post 'plates/:id/products/new', to: 'dishes_products#create'
  get 'plates/:id/products/edit/:registro', to: 'dishes_products#edit'
  post 'plates/:id/products/edit/:registro', to: 'dishes_products#update'
  delete 'plates/:id/products/:registro', to: 'dishes_products#destroy'

  match "*path" => 'auth#notFound', via: [:get, :post]

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :quesionsAnswersPermissions

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @questions = Question.all
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
    @questions = Question.all
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to answers_path, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answers_path, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :text_answer)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<div class="col-md-6 forms-centers">

<%= form_for(answer) do |f| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %>
    <%= f.select :question_id, options_for_select(@questions.map{ |c| [c.text_question, c.id ]},answer.question_id),{}, { class: 'form-control form-control-sm'} %>
  </div>

  <div class="field">
    <%= f.label :text_answer %>
    <%= f.text_field :text_answer, class: "form-control form-control-sm" %>
  </div>
<br>
  <div class="actions">
    <%= link_to '<<', answers_path ,class: "btn btn-default btn-sm" %>
    <%= f.submit 'Save',class: "btn btn-default btn-sm" %>
  </div>
<% end %>


</div>

app/views/answers/edit.html.erb
<h1 class="head-title-form"> Editing Answer</h1>
<div class="container">
<%= render 'form', answer: @answer %>
</div>

app/views/answers/index.html.erb
<h1 class="head-title-form"> Answers</h1>
<div class="container">
  <% if !notice.nil? %>
  <p id="notice" class="notice-good"><%= notice %></p>
  <% end %>
  <% if (flash[:notice_bad])  %>
  <p id="notice_bad" class="notice-bad"><%= flash[:notice_bad] %></p>
  <% end %>
  <div class="table-responsive">
  <table class="table table-sm">

  <thead>
    <tr>
      <th>Question</th>
      <th>Text answer</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question.text_question  %></td>
        <td><%= answer.text_answer %></td>
        <!--<td><%= link_to 'Show', answer,class:"btn btn-default btn-sm" %></td>-->
        <td><%= link_to 'Edit', edit_answer_path(answer),class:"btn btn-default btn-sm" %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-default btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Answer', new_answer_path, class: "font_size_no_p" %>

app/views/answers/new.html.erb
<h1 class="head-title-form"> New Answer</h1>
<div class="container">
<%= render 'form', answer: @answer %>

</div>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>Text answer:</strong>
  <%= @answer.text_answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>